---
gather_information:
  description: Use the SerperDevTool to search the internet for the latest scientific
    discoveries and tech breakthroughs in {year}.
  expected_output: A collection of articles, papers, and videos on recent scientific
    and tech advancements.
  async_execution: false
  agent: researcher
find_videos:
  description: Use the YoutubeVideoSearchTool to find relevant videos that discuss
    recent scientific and tech advancements.
  expected_output: A list of YouTube videos that provide additional insights into
    the latest discoveries and breakthroughs.
  async_execution: false
  agent: researcher
extract_details:
  description: Use the ScrapeWebsiteTool to extract detailed information from authoritative
    science and tech websites.
  expected_output: Detailed information from reputable websites about the latest scientific
    and tech advancements.
  async_execution: false
  agent: researcher
summarize_information:
  description: Summarize the gathered information into key points and insights. Extract
    main concepts the discoveries and breakthroughs are based on.
  expected_output: A concise summary and a list of related main concepts of the latest
    scientific discoveries and tech breakthroughs.
  async_execution: false
  agent: summarizer
  context:
  - gather_information
  - find_videos
  - extract_details
create_script:
  description: Create a structured engaging, innovative blog post and video script
    based on the summarized information.
  expected_output: A well-written blog post and video script on the latest scientific
    discoveries and tech breakthroughs.
  async_execution: false
  agent: writer
  context:
  - summarize_information
